---
apiVersion: v1
kind: Service
metadata:
  name: tetris-service
spec:
  selector:
    app: php
  ports:
  - protocol: TCP
    port: 82               # Expose port 80
    targetPort: 82
  type: LoadBalancer
