pipeline{
    agent any
    stages {
        stage('Checkout from Git'){
            steps{
                git branch: 'master', url: 'https://github.com/beadeveloper9789/phpjenkins.git'
            }
        }
        stage('Terraform version'){
             steps{
                 sh 'terraform --version'
             }
        }
        stage('Terraform init'){
             steps{
                 dir('Eks-terraform') {
                      sh 'terraform init -migrate-state'
                   }      
             }
        }
        stage('Terraform validate'){
             steps{
                 dir('Eks-terraform') {
                      sh 'terraform validate '
                   }      
             }
        }
        stage('Terraform plan'){
             steps{
                 dir('Eks-terraform') {
                      sh 'terraform plan'
                   }      
             }
        }
        stage('Terraform apply'){
             steps{
                 dir('Eks-terraform') {
                      sh 'terraform apply --auto-approve'
                   }      
             }
        }
    }
}
